namespace EasySourceGenerators.Abstractions;

/// <summary>
/// Method body generated by this source generator will be a return of a constant value calculated by executing this method during compilation.
/// This is the default behavior of <see cref="MethodBodyGenerator"/> when no other generation method is explicitly provided.
/// </summary>
/// <example>
/// The following code:
/// <code>
/// public partial int GetTwoSquared();
///
/// [<see cref="MethodBodyGenerator"/>(nameof(GetTwoSquared))]
/// [<see cref="GenerateCompileTimeConstant"/>]
/// public static int GetTwoSquared_Generator() => 2 * 2;
/// </code>
/// will generate the following method:
/// <code>public int GetTwoSquared() => 4;</code>
/// </example>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public class GenerateCompileTimeConstant : Attribute;