using System.Text;

namespace EasySourceGenerators.Generators.SourceEmitting;

/// <summary>
/// Emits C# source code for partial method implementations.
/// Works with plain data records, independent of Roslyn symbol types.
/// </summary>
internal static class PartialMethodSourceEmitter
{
    /// <summary>
    /// Generates a complete C# source file containing a partial method implementation
    /// that returns the given literal value.
    /// </summary>
    internal static string Emit(PartialMethodEmitData data, string? returnValueLiteral)
    {
        StringBuilder builder = new();
        AppendFileHeader(builder, data);

        if (!data.ReturnsVoid)
        {
            builder.AppendLine($"        return {returnValueLiteral ?? "default"};");
        }

        AppendClosingBraces(builder);
        return builder.ToString();
    }

    /// <summary>
    /// Generates a complete C# source file containing a partial method implementation
    /// with the given body lines (already indented to the method body level).
    /// </summary>
    internal static string EmitWithBody(PartialMethodEmitData data, string bodyLines)
    {
        StringBuilder builder = new();
        AppendFileHeader(builder, data);
        builder.AppendLine(bodyLines);
        AppendClosingBraces(builder);
        return builder.ToString();
    }

    /// <summary>
    /// Appends the auto-generated file header, namespace declaration, type declaration,
    /// and method signature opening to the <see cref="StringBuilder"/>.
    /// </summary>
    internal static void AppendFileHeader(StringBuilder builder, PartialMethodEmitData data)
    {
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine($"// Generated by {data.GeneratorFullName} for method '{data.MethodName}'.");
        builder.AppendLine("#pragma warning disable");
        builder.AppendLine();

        if (data.NamespaceName != null)
        {
            builder.AppendLine($"namespace {data.NamespaceName};");
            builder.AppendLine();
        }

        builder.AppendLine($"{data.TypeModifiers} {data.TypeKeyword} {data.TypeName}");
        builder.AppendLine("{");
        builder.AppendLine($"    {data.AccessibilityKeyword} {data.MethodModifiers} {data.ReturnTypeName} {data.MethodName}({data.ParameterList})");
        builder.AppendLine("    {");
    }

    /// <summary>
    /// Appends closing braces for the method and type declarations.
    /// </summary>
    internal static void AppendClosingBraces(StringBuilder builder)
    {
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }
}
